/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 EnderChest.glb 
Author: CanYuTsai (https://sketchfab.com/canyutsai1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-animated-ender-chest-86dcfd5ed3a54dee854454400db4d3d2
Title: Minecraft Animated Ender Chest
*/

/* eslint-disable react/no-unknown-property */
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function EnderChest(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/animated/3d/EnderChest.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.873}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="chest_6" position={[0, 0.5, 0]} rotation={[0, 0, -Math.PI]}>
                <group name="Lid_3" position={[0, -0.125, -0.438]}>
                  <group name="e516d948-1af8-52ff-c195-b07266936ce7_1" position={[0, -0.375, 0.438]}>
                    <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['download_54.png']} />
                  </group>
                  <group name="a8485cb4-c06f-afd9-9293-9865a0d32ee5_2" position={[0, -0.156, 0.438]} rotation={[0, 0, -Math.PI]}>
                    <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['download_54.png']} />
                  </group>
                </group>
                <group name="block_5" position={[0, -1.5, 0]}>
                  <group name="0ddf48a8-b575-713f-ba1c-d732f96101cf_4">
                    <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['download_54.png']} />
                  </group>
                </group>
                <group name="6e2da91e-9722-6cba-1061-d46d14d9b13d_0" position={[0, 0.188, 0]} rotation={[-Math.PI, 0, 0]}>
                  <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['download_54.png']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/animated/3d/EnderChest.glb')
