/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 StatisticArrow.glb 
Author: cig3d (https://sketchfab.com/cig3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/statistic-charts-with-arrow-86f9238bdaf44e098b6da4d82ee1861f
Title: Statistic Charts With Arrow
*/

/* eslint-disable react/no-unknown-property */
import { useGLTF } from '@react-three/drei'

export function StatisticArrow(props) {
  const { nodes, materials } = useGLTF('/animated/3d/StatisticArrow.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.002']} position={[-0.248, 0, 0]} scale={[0.324, 0.324, 0.279]} />
        <mesh geometry={nodes.Cube001_0.geometry} material={materials['Material.003']} position={[0.607, 0, 0]} scale={[0.324, 0.324, 0.529]} />
        <mesh geometry={nodes.Cube002_0.geometry} material={materials['Material.004']} position={[1.443, 0, 0]} scale={[0.324, 0.324, 0.779]} />
        <mesh geometry={nodes.Cube003_0.geometry} material={materials['Material.001']} position={[-1.476, -0.053, 0.211]} rotation={[0, 0.57, 0]} scale={[0.089, 0.075, 0.576]} />
      </group>
    </group>
  )
}

useGLTF.preload('/animated/3d/StatisticArrow.glb')
