/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gamer_laptop_editable_display.glb 
Author: Özlem Çandır (https://sketchfab.com/OzlemCandir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gamer-laptop-editable-display-faa3d29ff5404b509f308f391b70d3e0
Title: Gamer Laptop (Editable Display)
*/

/* eslint-disable react/no-unknown-property */
import { useGLTF } from '@react-three/drei'

export function GamerLaptop(props) {
  const { nodes, materials } = useGLTF('/animated/3d/GamerLaptop.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[184.897, 0.032, 217.148]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cylinder003_Laptop_0.geometry} material={materials.Laptop} />
          <mesh geometry={nodes.Cylinder003_Laptop001_0.geometry} material={materials['Laptop.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/animated/3d/GamerLaptop.glb')
